### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Auditormadness9** [g3th/Windscribe-Signup#2]
```python
Contacting Temp Email API endpoint
Traceback (most recent call last):
  File "S:\Windscribe-Signup\windscribe.py", line 116, in <module>
    email = str(tempmail.create_an_email_address()) + '@developermail.com'
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Windscribe-Signup\email_confirmation.py", line 26, in create_an_email_address
    self.temp_email = self.api_endpoint + self.created_email_address['name']
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by g3th** [comment]
Hi there,

The error indicates that no email address has been created. Hence, the TypeError, since the Json dictionary returns 'None' for [result]. This is what the 'PUT' method returns when creating an email inbox with developermail api:

{"success":false,"errors":[{"code":500,"message":"No space left on device","detail":"No space left on device"}],"result":null}

Unfortunately there is little I can do, apart from using another free temp email api service. I would suggest either contacting developermail themselves and asking why there is "No space left on device", or trying the program sometimes later.

I will close the issue, but you are still free to ask your questions here.

**Comment by Auditormadness9** [comment]
Maybe try [InstAddr](https://m.kuku.lu/en.php)?
